# parameters:
# # labo_3_bundle.example.class: labo\Bundle\TestmanuBundle\Example

# services:

#     ###################################
#     ### OUTILS GÉNÉRIQUES
#     ###################################

    # Fonctions textes utiles et pratiques pour utilisation dans TWIG
    labo3bundle.textutilities:
        class: labo\Bundle\TestmanuBundle\services\aetools\twigAetools
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    # Fonctionnalités sur les textes (notamment l'entité richtext)
    labo3bundle.texttools:
        class: labo\Bundle\TestmanuBundle\services\aetools\richtextsAetools
        arguments: [@service_container]

    # Fonctionnalités de requêtes et dossiers/fichiers
    labo3bundle.aetools:
        class: labo\Bundle\TestmanuBundle\services\aetools\aetools
        arguments: [@service_container]

#     # Fonctionnalités de dates/heures
#     labo3bundle.aedates:
#         class: labo\Bundle\TestmanuBundle\services\aetools\aedates
#         arguments: [@service_container]

#     # Fonctionnalités de parametres du site
#     labo3bundle.parametre:
#         class: labo\Bundle\TestmanuBundle\services\aetools\parametre
#         arguments: [@service_container]

    # Fonctionnalités de manipulations d'images
    labo3bundle.imagetools:
        class: labo\Bundle\TestmanuBundle\services\aetools\imageAetools
        arguments: [@service_container]

#     # Fonctionnalités de parsage XML
#     labo3bundle.XMLparser:
#         class: labo\Bundle\TestmanuBundle\services\aetools\XMLparser
#         arguments: []

#     ###################################
#     ### OUTILS ENTITÉS
#     ###################################

    # Fonctionnalités de base pour les entités
    labo3bundle.entities:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\entitiesGeneric
        arguments: [@service_container]

    # Fonctionnalités de gestion des versions (sociétés)
    labo3bundle.version:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\version
        arguments: [@service_container]

#     # Fonctionnalités de gestion des pages web
#     labo3bundle.pageweb:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\pageweb
#         arguments: [@service_container]

#     # Fonctionnalités de gestion des collections
#     labo3bundle.collection:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\collection
#         arguments: [@service_container]

#     # Fonctionnalités de gestion des votes
#     labo3bundle.votes:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\votes
#         arguments: [@service_container]

#     # Fonctionnalités de gestion des visites sur le site
#     labo3bundle.visite:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\visite
#         arguments: [@service_container]

#     # Fonctionnalités de categorie
#     labo3bundle.categorie:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\categorie
#         arguments: [@service_container]

#     # Fonctionnalités pour articles
#     labo3bundle.article:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\article
#         arguments: [@service_container]

#     # Atelier créatif et fiches
#     labo3bundle.atelierCreatif:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\atelierCreatif
#         arguments: [@service_container]

#     # magasins
#     labo3bundle.magasin:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\magasin
#         arguments: [@service_container]

#     # videos
#     labo3bundle.video:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\video
#         arguments: [@service_container]

#     # évènements
#     labo3bundle.events:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\evenement
#         arguments: [@service_container]

#     # presse
#     labo3bundle.presse:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\presse
#         arguments: [@service_container]

#     # factures
#     labo3bundle.facture:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\facture
#         arguments: [@service_container]

#     # aelogs
#     labo3bundle.aelog:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\aelog
#         arguments: [@service_container]

#     # Fonctionnalités de gestion du panier d'achat
#     # -> synthèses, ajouts, suppressions, etc. de produits dans le panier
#     labo3bundle.panier:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\panier
#         arguments: [@service_container]
#         # scope: request

#     labo3bundle.directeditor:
#         class: labo\Bundle\TestmanuBundle\services\entitiesServices\directeditor
#         arguments: [@service_container]
#         tags:
#             - { name: twig.extension }

#     ###################################
#     ### EVENT LISTENER AU DÉMARRAGE DE REQUETE PRINCIPALE
#     ###################################

#     # EventListerner sur paramètres généraux du site
#     labo3bundle.site_listener:
#         class: labo\Bundle\TestmanuBundle\eventListeners\siteListener\siteListener
#         arguments: [@service_container]
#         tags:
#             - { name: kernel.event_listener, event: kernel.controller, method: load_session_items }


    ###################################
    ### EVENT LISTENER SUR DOCTRINE ENTITIES
    ###################################

    # Utilitaire de gestion sur les entités
    labo3bundle.entityUtils:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\entityListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: postRemove }


#     ###################################
#     ### ELEMENTS DE FORMULAIRES
#     ###################################

#     # Éléments de formulaires personnalisés
#     form.type.datepicker:
#         class: labo\Bundle\TestmanuBundle\Form\Type\DatepickerType
#         arguments:
#             - "%formatDate%"
#         tags:
#             - { name: form.type, alias: datepicker }

#     form.type.datepicker2:
#         class: labo\Bundle\TestmanuBundle\Form\Type\Datepicker2Type
#         arguments:
#             - "%formatDate%"
#         tags:
#             - { name: form.type, alias: datepicker2 }

#     form.type.datepicker2alldates:
#         class: labo\Bundle\TestmanuBundle\Form\Type\Datepicker2alldatesType
#         arguments:
#             - "%formatDate%"
#         tags:
#             - { name: form.type, alias: datepicker2alldates }

#     form.type.richtext:
#         class: labo\Bundle\TestmanuBundle\Form\Type\richtextType
#         tags:
#             - { name: form.type, alias: richtext }

#     form.type.gender:
#         class: labo\Bundle\TestmanuBundle\Form\Type\GenderType
#         tags:
#             - { name: form.type, alias: gender }

#     form.type.routes:
#         class: labo\Bundle\TestmanuBundle\Form\Type\RoutesType
#         arguments: [@service_container]
#         tags:
#             - { name: form.type, alias: routes }



