parameters:
    # labo_bundle.example.class: laboBundle\Example

services:

#     ###################################
#     ### OUTILS GÉNÉRIQUES
#     ###################################

    # Fonctions textes utiles et pratiques pour utilisation dans TWIG
    labobundle.textutilities:
        class: laboBundle\services\aetools\twigAetools
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    # Fonctionnalités sur les textes (notamment l'entité richtext)
    labobundle.texttools:
        class: laboBundle\services\aetools\richtextsAetools
        arguments: [@service_container]

    # Fonctionnalités de requêtes et dossiers/fichiers
    labobundle.aetools:
        class: laboBundle\services\aetools\aetools
        arguments: [@service_container]

#     # Fonctionnalités de dates/heures
#     labobundle.aedates:
#         class: laboBundle\services\aetools\aedates
#         arguments: [@service_container]

#     # Fonctionnalités de parametres du site
#     labobundle.parametre:
#         class: laboBundle\services\aetools\parametre
#         arguments: [@service_container]

    # Fonctionnalités de manipulations d'images
    labobundle.imagetools:
        class: laboBundle\services\aetools\imageAetools
        arguments: [@service_container]

#     # Fonctionnalités de parsage XML
#     labobundle.XMLparser:
#         class: laboBundle\services\aetools\XMLparser
#         arguments: []

#     ###################################
#     ### OUTILS ENTITÉS
#     ###################################

    # Fonctionnalités de base pour les entités
    labobundle.entities:
        class: laboBundle\services\entitiesServices\entitiesGeneric
        arguments: [@service_container]

    # Fonctionnalités de gestion des versions (sociétés)
    labobundle.version:
        class: laboBundle\services\entitiesServices\version
        arguments: [@service_container]

#     # Fonctionnalités de gestion des pages web
#     labobundle.pageweb:
#         class: laboBundle\services\entitiesServices\pageweb
#         arguments: [@service_container]

#     # Fonctionnalités de gestion des collections
#     labobundle.collection:
#         class: laboBundle\services\entitiesServices\collection
#         arguments: [@service_container]

#     # Fonctionnalités de gestion des votes
#     labobundle.votes:
#         class: laboBundle\services\entitiesServices\votes
#         arguments: [@service_container]

#     # Fonctionnalités de gestion des visites sur le site
#     labobundle.visite:
#         class: laboBundle\services\entitiesServices\visite
#         arguments: [@service_container]

#     # Fonctionnalités de categorie
#     labobundle.categorie:
#         class: laboBundle\services\entitiesServices\categorie
#         arguments: [@service_container]

#     # Fonctionnalités pour articles
#     labobundle.article:
#         class: laboBundle\services\entitiesServices\article
#         arguments: [@service_container]

#     # Atelier créatif et fiches
#     labobundle.atelierCreatif:
#         class: laboBundle\services\entitiesServices\atelierCreatif
#         arguments: [@service_container]

#     # magasins
#     labobundle.magasin:
#         class: laboBundle\services\entitiesServices\magasin
#         arguments: [@service_container]

#     # videos
#     labobundle.video:
#         class: laboBundle\services\entitiesServices\video
#         arguments: [@service_container]

#     # évènements
#     labobundle.events:
#         class: laboBundle\services\entitiesServices\evenement
#         arguments: [@service_container]

#     # presse
#     labobundle.presse:
#         class: laboBundle\services\entitiesServices\presse
#         arguments: [@service_container]

#     # factures
#     labobundle.facture:
#         class: laboBundle\services\entitiesServices\facture
#         arguments: [@service_container]

#     # aelogs
#     labobundle.aelog:
#         class: laboBundle\services\entitiesServices\aelog
#         arguments: [@service_container]

#     # Fonctionnalités de gestion du panier d'achat
#     # -> synthèses, ajouts, suppressions, etc. de produits dans le panier
#     labobundle.panier:
#         class: laboBundle\services\entitiesServices\panier
#         arguments: [@service_container]
#         # scope: request

#     labobundle.directeditor:
#         class: laboBundle\services\entitiesServices\directeditor
#         arguments: [@service_container]
#         tags:
#             - { name: twig.extension }

#     ###################################
#     ### EVENT LISTENER AU DÉMARRAGE DE REQUETE PRINCIPALE
#     ###################################

#     # EventListerner sur paramètres généraux du site
#     labobundle.site_listener:
#         class: laboBundle\eventListeners\siteListener\siteListener
#         arguments: [@service_container]
#         tags:
#             - { name: kernel.event_listener, event: kernel.controller, method: load_session_items }


    ###################################
    ### EVENT LISTENER SUR DOCTRINE ENTITIES
    ###################################

    # Utilitaire de gestion sur les entités
    labobundle.entityUtils:
        class: laboBundle\services\entitiesServices\entityListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: postRemove }


#     ###################################
#     ### ELEMENTS DE FORMULAIRES
#     ###################################

#     # Éléments de formulaires personnalisés
#     form.type.datepicker:
#         class: laboBundle\Form\Type\DatepickerType
#         arguments:
#             - "%formatDate%"
#         tags:
#             - { name: form.type, alias: datepicker }

#     form.type.datepicker2:
#         class: laboBundle\Form\Type\Datepicker2Type
#         arguments:
#             - "%formatDate%"
#         tags:
#             - { name: form.type, alias: datepicker2 }

#     form.type.datepicker2alldates:
#         class: laboBundle\Form\Type\Datepicker2alldatesType
#         arguments:
#             - "%formatDate%"
#         tags:
#             - { name: form.type, alias: datepicker2alldates }

#     form.type.richtext:
#         class: laboBundle\Form\Type\richtextType
#         tags:
#             - { name: form.type, alias: richtext }

#     form.type.gender:
#         class: laboBundle\Form\Type\GenderType
#         tags:
#             - { name: form.type, alias: gender }

#     form.type.routes:
#         class: laboBundle\Form\Type\RoutesType
#         arguments: [@service_container]
#         tags:
#             - { name: form.type, alias: routes }



