parameters:
    labo_bundle.aetools.route:    laboBundle\services\aetools
    labo_bundle.entities.route:   laboBundle\services\entitiesServices
    labo_bundle.framework.route:   laboBundle\services\framework
    labo_bundle.framework.modules.route:   laboBundle\services\framework\pagesModules

services:

#     ###################################
#     ### OUTILS GÉNÉRIQUES
#     ###################################

    # Fonctionnalités de requêtes et dossiers/fichiers
    labobundle.aetools:
        class: %labo_bundle.aetools.route%\aetools
        arguments: [@service_container]

    # Formalisation de format de réponse
    # labobundle.aeReponse:
    #     class: %labo_bundle.aetools.route%\aeReponse
    #     arguments: [@service_container]
    #     scope: prototype

    # Fonctions textes utiles et pratiques pour utilisation dans TWIG
    labobundle.textutilities:
        class: %labo_bundle.aetools.route%\twigAetools
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    # Fonctionnalités de dates/heures
    labobundle.aedates:
        class: %labo_bundle.aetools.route%\twigAedates
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

#     # Fonctionnalités de parametres du site
#     labobundle.parametre:
#         class: %labo_bundle.aetools.route%\parametre
#         arguments: [@service_container]


#     ###################################
#     ### OUTILS IMAGES
#     ###################################

    # Fonctionnalités de manipulations d'images
    labobundle.imagetools:
        class: %labo_bundle.aetools.route%\imageAetools
        arguments: [@service_container]

#     # Fonctionnalités de parsage XML
#     labobundle.XMLparser:
#         class: %labo_bundle.aetools.route%\XMLparser
#         arguments: []

    # Fonctionnalités de lecture CSV
    labobundle.CSVreader:
        class: %labo_bundle.aetools.route%\CSVreader
        arguments: []


#     ###################################
#     ### OUTILS ENTITÉS
#     ###################################

    # Fonctionnalités de base pour les entités
    labobundle.entities:
        class: %labo_bundle.entities.route%\entitesService
        arguments: [@service_container]

    # # Fonctionnalités de gestion des versions (sociétés)
    # labobundle.version:
    #     class: %labo_bundle.entities.route%\version
    #     arguments: [@service_container]

    # Fonctionnalités de gestion des versions (sociétés)
    labobundle.categorie:
        class: %labo_bundle.entities.route%\categorie
        arguments: [@service_container]


#     ###################################
#     ### TEMPLATE PAGES
#     ###################################

    # gestion des données primaires
    labobundle.primarydata:
        class: %labo_bundle.framework.modules.route%\primarydata
        # arguments: [@service_container]
        # tags:
        #     - { name: kernel.event_listener, event: kernel.controller, method: serviceEventInit }

    # gestion des pages
    labobundle.pages:
        class: %labo_bundle.framework.route%\pages
        arguments: [@service_container]

    # gestion des pages
    labobundle.pages.labo:
        class: %labo_bundle.framework.route%\pageslabo
        arguments: [@service_container]


#     ###################################
#     ### EVENT LISTENER AU DÉMARRAGE DE REQUETE PRINCIPALE
#     ###################################

    # EventListerner sur paramètres généraux du site
    labobundle.site_listener:
        class: laboBundle\eventListeners\siteListener\siteListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: load_session_items }


    ###################################
    ### EVENT LISTENER SUR DOCTRINE ENTITIES
    ###################################

    # Utilitaire de gestion sur les entités
    labobundle.entityUtils:
        class: %labo_bundle.entities.route%\entityListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: postRemove }


#     ###################################
#     ### ELEMENTS DE FORMULAIRES
#     ###################################

#     # Éléments de formulaires personnalisés
#     form.type.datepicker:
#         class: laboBundle\Form\Type\DatepickerType
#         arguments:
#             - "%formatDate%"
#         tags:
#             - { name: form.type, alias: datepicker }

#     form.type.datepicker2:
#         class: laboBundle\Form\Type\Datepicker2Type
#         arguments:
#             - "%formatDate%"
#         tags:
#             - { name: form.type, alias: datepicker2 }

#     form.type.datepicker2alldates:
#         class: laboBundle\Form\Type\Datepicker2alldatesType
#         arguments:
#             - "%formatDate%"
#         tags:
#             - { name: form.type, alias: datepicker2alldates }

#     form.type.richtext:
#         class: laboBundle\Form\Type\richtextType
#         tags:
#             - { name: form.type, alias: richtext }

#     form.type.gender:
#         class: laboBundle\Form\Type\GenderType
#         tags:
#             - { name: form.type, alias: gender }

#     form.type.routes:
#         class: laboBundle\Form\Type\RoutesType
#         arguments: [@service_container]
#         tags:
#             - { name: form.type, alias: routes }



