<?php

namespace labo\Bundle\TestmanuBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\base_laboRepository;
// aeReponse
use labo\Bundle\TestmanuBundle\services\aetools\aeReponse;

/**
 * statutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class statutRepository extends base_laboRepository {

	/**
	 * Renvoie true si la demande correspond correspond
	 * ex. : pour l'entité "baseL0_entity" -> "isBaseL0_entity" renvoie true
	 * @return boolean
	 */
	public function __call($name, $arguments = null) {
		switch ($name) {
			case 'is'.ucfirst($this->getName()):
				$reponse = true;
				break;
			default:
				$reponse = false;
				break;
		}
		return $reponse;
	}

	/**
	 * Renvoie le nom de l'entité parent
	 * @return string
	 */
	public function getParentName() {
		return parent::getName();
	}

	/**
	 * Renvoie le nom de l'entité
	 * @return string
	 */
	public function getName() {
		return 'statutRepository';
	}

	/** 
	 * Renvoie la(les) valeur(s) par défaut --> ATTENTION : dans un array()
	 * @param $defaults = liste des éléments par défaut
	 */
	public function defaultVal($defaults = null) {
		if($defaults === null) $defaults = array("Actif");
		$qb = $this->createQueryBuilder('element');
		$qb->where($qb->expr()->in('element.nom', $defaults));
		return $qb->getQuery()->getResult();
	}

	public function getInactif() {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.nom = :inactif')
			->setParameter('inactif', self::STATUT_INACTIF)
			->setMaxResults(1);
		return $qb->getQuery()->getOneOrNullResult();
	}

	public function defaultValClosure($role = "ROLE_USER") {
		$list = null;
		switch($role) {
			case "ROLE_EDITOR":
				$list = array("Actif", "Inactif");
				break;
			case "ROLE_USER":
				$list = array("Actif", "Inactif");
				break;
			case "ROLE_ADMIN":
				$list = array("Actif", "Inactif");
				break;
			case "ROLE_SUPER_ADMIN":
				// all
				break;
			default:
				$list = array("Actif", "Inactif");
				break;
		}
		$qb = $this->createQueryBuilder('element');
		if(is_array($list)) $qb->where($qb->expr()->in('element.nom', $list));
		return $qb;
	}

}
